# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ResumoCamada
                                 A QGIS plugin
 Mostra resumo da camada ativa e exporta CSV e PDF.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-27
        copyright            : (C) 2026 by Leandro Eloi
        email                : leandroodev001@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ResumoCamada class from file ResumoCamada.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .resumo_camada import ResumoCamada
    return ResumoCamada(iface)
