# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ResumoCamada
                                 A QGIS plugin
 Mostra resumo da camada ativa e exporta CSV e PDF.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-27
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Leandro Eloi
        email                : leandroodev001@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import csv
import os
from datetime import datetime

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon, QFont, QColor
from qgis.PyQt.QtWidgets import QAction, QMessageBox, QFileDialog

from qgis.core import (
    QgsProject,
    QgsPrintLayout,
    QgsLayoutItemLabel,
    QgsLayoutItemMap,
    QgsLayoutItemPicture,
    QgsLayoutPoint,
    QgsLayoutSize,
    QgsLayoutExporter,
    QgsUnitTypes,
    QgsMapLayerType,
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransform,
    QgsGeometry,
    QgsRectangle,
    QgsFillSymbol,
    QgsSingleSymbolRenderer
)

from .resources import *
from .resumo_camada_dialog import ResumoCamadaDialog


class ResumoCamada:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)

        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'ResumoCamada_{}.qm'.format(locale)
        )

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr(u'&Resumo de Camada')
        self.first_start = None

    def tr(self, message):
        return QCoreApplication.translate('ResumoCamada', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None
    ):
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        icon_path = ':/plugins/resumo_camada/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Resumo de Camada'),
            callback=self.run,
            parent=self.iface.mainWindow()
        )
        self.first_start = True

    def unload(self):
        for action in self.actions:
            self.iface.removePluginMenu(self.tr(u'&Resumo de Camada'), action)
            self.iface.removeToolBarIcon(action)

    def tipo_geometria_texto(self, layer):
        tipos = {
            0: 'Ponto',
            1: 'Linha',
            2: 'Polígono',
            4: 'Sem geometria'
        }
        return tipos.get(layer.geometryType(), 'Desconhecido')

    def formatar_numero_br(self, valor, casas=2):
        texto = f'{valor:,.{casas}f}'
        return texto.replace(',', 'X').replace('.', ',').replace('X', '.')

    def obter_feicoes_relatorio(self, layer):
        if layer.selectedFeatureCount() > 0:
            return list(layer.selectedFeatures()), 'Feições selecionadas'
        return list(layer.getFeatures()), 'Todas as feições da camada'

    def obter_crs_area(self, layer):
        projeto = QgsProject.instance()
        crs_geo = QgsCoordinateReferenceSystem('EPSG:4326')

        centro = layer.extent().center()
        if layer.crs() != crs_geo:
            transform = QgsCoordinateTransform(layer.crs(), crs_geo, projeto)
            centro = transform.transform(centro)

        lon = centro.x()
        lat = centro.y()
        zona = int((lon + 180) / 6) + 1

        if lat >= 0:
            epsg = 32600 + zona
        else:
            epsg = 32700 + zona

        return QgsCoordinateReferenceSystem(f'EPSG:{epsg}')

    def analisar_feicoes(self, layer):
        projeto = QgsProject.instance()
        crs_geo = QgsCoordinateReferenceSystem('EPSG:4326')
        crs_area = self.obter_crs_area(layer)

        feicoes, escopo = self.obter_feicoes_relatorio(layer)

        transform_area = QgsCoordinateTransform(layer.crs(), crs_area, projeto)
        transform_geo = QgsCoordinateTransform(layer.crs(), crs_geo, projeto)

        detalhes = []
        area_total_m2 = 0.0
        extent = None

        for i, feat in enumerate(feicoes, start=1):
            if not feat.hasGeometry():
                continue

            geom_original = QgsGeometry(feat.geometry())
            bbox = geom_original.boundingBox()

            if extent is None:
                extent = QgsRectangle(bbox)
            else:
                extent.combineExtentWith(bbox)

            area_m2 = 0.0
            perimetro_m = 0.0

            if layer.geometryType() == 2:
                geom_area = QgsGeometry(feat.geometry())
                geom_area.transform(transform_area)
                area_m2 = abs(geom_area.area())
                perimetro_m = abs(geom_area.length())

            geom_geo = QgsGeometry(feat.geometry())
            geom_geo.transform(transform_geo)
            centroide = geom_geo.centroid().asPoint()

            detalhes.append({
                'indice': i,
                'feature_id': feat.id(),
                'area_m2': area_m2,
                'perimetro_m': perimetro_m,
                'area_m2_txt': f"{self.formatar_numero_br(area_m2, 2)} m²",
                'area_ha_txt': f"{self.formatar_numero_br(area_m2 / 10000.0, 4)} ha",
                'area_km2_txt': f"{self.formatar_numero_br(area_m2 / 1000000.0, 6)} km²",
                'perimetro_txt': f"{self.formatar_numero_br(perimetro_m, 2)} m",
                'centroide_lon': centroide.x(),
                'centroide_lat': centroide.y(),
                'centroide_lat_txt': self.formatar_numero_br(centroide.y(), 6),
                'centroide_lon_txt': self.formatar_numero_br(centroide.x(), 6)
            })

            area_total_m2 += area_m2

        diff_m2 = None
        if len(detalhes) >= 2:
            diff_m2 = abs(detalhes[0]['area_m2'] - detalhes[1]['area_m2'])

        return detalhes, escopo, area_total_m2, diff_m2, extent

    def obter_resumo(self, layer):
        detalhes, escopo, area_total_m2, diff_m2, extent = self.analisar_feicoes(layer)

        resumo = {
            'nome_camada': layer.name(),
            'total_feicoes': len(detalhes),
            'tipo_geometria': self.tipo_geometria_texto(layer),
            'data_exportacao': datetime.now().strftime('%d/%m/%Y %H:%M:%S'),
            'escopo': escopo,
            'detalhes': detalhes,
            'extent': extent,
            'area_total_m2': area_total_m2,
            'area_total_m2_txt': f"{self.formatar_numero_br(area_total_m2, 2)} m²",
            'area_total_ha_txt': f"{self.formatar_numero_br(area_total_m2 / 10000.0, 4)} ha",
            'area_total_km2_txt': f"{self.formatar_numero_br(area_total_m2 / 1000000.0, 6)} km²",
            'diferenca_m2': diff_m2,
            'diferenca_m2_txt': None,
            'diferenca_ha_txt': None,
            'diferenca_km2_txt': None
        }

        if diff_m2 is not None:
            resumo['diferenca_m2_txt'] = f"{self.formatar_numero_br(diff_m2, 2)} m²"
            resumo['diferenca_ha_txt'] = f"{self.formatar_numero_br(diff_m2 / 10000.0, 4)} ha"
            resumo['diferenca_km2_txt'] = f"{self.formatar_numero_br(diff_m2 / 1000000.0, 6)} km²"

        return resumo

    def resumo_texto(self, resumo):
        linhas = [
            f"Camada: {resumo['nome_camada']}",
            f"Escopo: {resumo['escopo']}",
            f"Feições: {resumo['total_feicoes']}",
            f"Geometria: {resumo['tipo_geometria']}",
            f"Data: {resumo['data_exportacao']}",
            f"Área total: {resumo['area_total_m2_txt']}",
            f"Área total em hectares: {resumo['area_total_ha_txt']}",
            f"Área total em km²: {resumo['area_total_km2_txt']}"
        ]

        if resumo['diferenca_m2_txt'] is not None:
            linhas.extend([
                f"Diferença área 1 x área 2: {resumo['diferenca_m2_txt']}",
                f"Diferença em hectares: {resumo['diferenca_ha_txt']}",
                f"Diferença em km²: {resumo['diferenca_km2_txt']}"
            ])

        return '\n'.join(linhas)

    def texto_area_card(self, det):
        return (
            f"Tamanho: {det['area_m2_txt']}\n"
            f"Hectares: {det['area_ha_txt']}\n"
            f"Km²: {det['area_km2_txt']}\n"
            f"Perímetro: {det['perimetro_txt']}\n"
            f"Latitude: {det['centroide_lat_txt']}\n"
            f"Longitude: {det['centroide_lon_txt']}"
        )

    def dados_dialogo(self, resumo):
        if resumo['diferenca_m2_txt'] is not None:
            obs = 'Comparação calculada entre as duas primeiras áreas do relatório.'
            dif_m2 = resumo['diferenca_m2_txt']
            dif_ha = resumo['diferenca_ha_txt']
            dif_km2 = resumo['diferenca_km2_txt']
        else:
            obs = 'A comparação é exibida automaticamente quando houver pelo menos 2 áreas.'
            dif_m2 = '-'
            dif_ha = '-'
            dif_km2 = '-'

        return {
            'camada': resumo['nome_camada'],
            'escopo': resumo['escopo'],
            'feicoes': str(resumo['total_feicoes']),
            'geometria': resumo['tipo_geometria'],
            'data': resumo['data_exportacao'],
            'area_m2': resumo['area_total_m2_txt'],
            'area_ha': resumo['area_total_ha_txt'],
            'area_km2': resumo['area_total_km2_txt'],
            'dif_m2': dif_m2,
            'dif_ha': dif_ha,
            'dif_km2': dif_km2,
            'obs_comparacao': obs
        }

    def exportar_csv(self, resumo):
        caminho_csv, _ = QFileDialog.getSaveFileName(
            self.iface.mainWindow(),
            'Salvar resumo em CSV',
            f"{resumo['nome_camada']}_resumo.csv",
            'CSV (*.csv)'
        )

        if not caminho_csv:
            return

        if not caminho_csv.lower().endswith('.csv'):
            caminho_csv += '.csv'

        with open(caminho_csv, 'w', newline='', encoding='utf-8-sig') as arquivo:
            writer = csv.writer(arquivo)

            writer.writerow(['Resumo da Camada'])
            writer.writerow(['Camada', resumo['nome_camada']])
            writer.writerow(['Escopo', resumo['escopo']])
            writer.writerow(['Feições', resumo['total_feicoes']])
            writer.writerow(['Geometria', resumo['tipo_geometria']])
            writer.writerow(['Data', resumo['data_exportacao']])
            writer.writerow(['Área total', resumo['area_total_m2_txt']])
            writer.writerow(['Área total em hectares', resumo['area_total_ha_txt']])
            writer.writerow(['Área total em km²', resumo['area_total_km2_txt']])

            if resumo['diferenca_m2_txt'] is not None:
                writer.writerow(['Diferença área 1 x área 2', resumo['diferenca_m2_txt']])

            writer.writerow([])
            writer.writerow([
                'Área',
                'Feature ID',
                'Área m²',
                'Área ha',
                'Área km²',
                'Perímetro',
                'Latitude',
                'Longitude'
            ])

            for det in resumo['detalhes']:
                writer.writerow([
                    f"Área {det['indice']}",
                    det['feature_id'],
                    det['area_m2_txt'],
                    det['area_ha_txt'],
                    det['area_km2_txt'],
                    det['perimetro_txt'],
                    det['centroide_lat_txt'],
                    det['centroide_lon_txt']
                ])

        QMessageBox.information(
            self.iface.mainWindow(),
            'Resumo de Camada',
            f'CSV exportado com sucesso:\n{caminho_csv}'
        )

    def configurar_estilo_layer(self, layer):
        if layer.geometryType() != 2:
            return

        simbolo = QgsFillSymbol.createSimple({
            'color': '255, 215, 64, 100',
            'outline_color': '120, 80, 0, 255',
            'outline_width': '0.9'
        })
        layer.setRenderer(QgsSingleSymbolRenderer(simbolo))
        layer.triggerRepaint()

    def exportar_pdf(self, layer, resumo):
        caminho_pdf, _ = QFileDialog.getSaveFileName(
            self.iface.mainWindow(),
            'Salvar resumo em PDF',
            f"{resumo['nome_camada']}_resumo.pdf",
            'PDF (*.pdf)'
        )

        if not caminho_pdf:
            return

        if not caminho_pdf.lower().endswith('.pdf'):
            caminho_pdf += '.pdf'

        self.configurar_estilo_layer(layer)

        projeto = QgsProject.instance()
        layout = QgsPrintLayout(projeto)
        layout.initializeDefaults()
        layout.setName(f"ResumoCamadaPDF_{resumo['nome_camada']}")

        cor_principal = QColor(24, 91, 127)
        cor_texto = QColor(55, 55, 55)

        logo_path = os.path.join(self.plugin_dir, 'icon.png')
        if os.path.exists(logo_path):
            logo = QgsLayoutItemPicture(layout)
            logo.setPicturePath(logo_path)
            logo.attemptMove(QgsLayoutPoint(12, 10, QgsUnitTypes.LayoutMillimeters))
            logo.attemptResize(QgsLayoutSize(14, 14, QgsUnitTypes.LayoutMillimeters))
            layout.addLayoutItem(logo)

        titulo = QgsLayoutItemLabel(layout)
        titulo.setText('Resumo de Camada')
        titulo.setFont(QFont('Arial', 18, QFont.Bold))
        titulo.setFontColor(cor_principal)
        titulo.adjustSizeToText()
        titulo.attemptMove(QgsLayoutPoint(30, 10, QgsUnitTypes.LayoutMillimeters))
        layout.addLayoutItem(titulo)

        subtitulo = QgsLayoutItemLabel(layout)
        subtitulo.setText(f"Relatório gerado em {resumo['data_exportacao']}")
        subtitulo.setFont(QFont('Arial', 8))
        subtitulo.setFontColor(cor_texto)
        subtitulo.adjustSizeToText()
        subtitulo.attemptMove(QgsLayoutPoint(30, 18, QgsUnitTypes.LayoutMillimeters))
        layout.addLayoutItem(subtitulo)

        resumo_titulo = QgsLayoutItemLabel(layout)
        resumo_titulo.setText('Resumo geral')
        resumo_titulo.setFont(QFont('Arial', 11, QFont.Bold))
        resumo_titulo.setFontColor(cor_principal)
        resumo_titulo.adjustSizeToText()
        resumo_titulo.attemptMove(QgsLayoutPoint(15, 34, QgsUnitTypes.LayoutMillimeters))
        layout.addLayoutItem(resumo_titulo)

        bloco_resumo = QgsLayoutItemLabel(layout)
        bloco_resumo.setText(self.resumo_texto(resumo))
        bloco_resumo.setFont(QFont('Arial', 8))
        bloco_resumo.adjustSizeToText()
        bloco_resumo.attemptMove(QgsLayoutPoint(15, 42, QgsUnitTypes.LayoutMillimeters))
        layout.addLayoutItem(bloco_resumo)

        resumo_bottom = 42 + bloco_resumo.rect().height()
        y_cards = resumo_bottom + 14
        card1_x = 15
        card2_x = 108

        card1_bottom = y_cards
        card2_bottom = y_cards

        if len(resumo['detalhes']) >= 1:
            area1_titulo = QgsLayoutItemLabel(layout)
            area1_titulo.setText(f"Área 1 (ID {resumo['detalhes'][0]['feature_id']})")
            area1_titulo.setFont(QFont('Arial', 10, QFont.Bold))
            area1_titulo.setFontColor(cor_principal)
            area1_titulo.adjustSizeToText()
            area1_titulo.attemptMove(QgsLayoutPoint(card1_x, y_cards, QgsUnitTypes.LayoutMillimeters))
            layout.addLayoutItem(area1_titulo)

            area1_texto = QgsLayoutItemLabel(layout)
            area1_texto.setText(self.texto_area_card(resumo['detalhes'][0]))
            area1_texto.setFont(QFont('Arial', 8))
            area1_texto.adjustSizeToText()
            area1_texto.attemptMove(QgsLayoutPoint(card1_x, y_cards + 8, QgsUnitTypes.LayoutMillimeters))
            layout.addLayoutItem(area1_texto)

            card1_bottom = (y_cards + 8) + area1_texto.rect().height()

        if len(resumo['detalhes']) >= 2:
            area2_titulo = QgsLayoutItemLabel(layout)
            area2_titulo.setText(f"Área 2 (ID {resumo['detalhes'][1]['feature_id']})")
            area2_titulo.setFont(QFont('Arial', 10, QFont.Bold))
            area2_titulo.setFontColor(cor_principal)
            area2_titulo.adjustSizeToText()
            area2_titulo.attemptMove(QgsLayoutPoint(card2_x, y_cards, QgsUnitTypes.LayoutMillimeters))
            layout.addLayoutItem(area2_titulo)

            area2_texto = QgsLayoutItemLabel(layout)
            area2_texto.setText(self.texto_area_card(resumo['detalhes'][1]))
            area2_texto.setFont(QFont('Arial', 8))
            area2_texto.adjustSizeToText()
            area2_texto.attemptMove(QgsLayoutPoint(card2_x, y_cards + 8, QgsUnitTypes.LayoutMillimeters))
            layout.addLayoutItem(area2_texto)

            card2_bottom = (y_cards + 8) + area2_texto.rect().height()

        cards_bottom = max(card1_bottom, card2_bottom)

        y_mapa_titulo = cards_bottom + 12
        y_mapa = y_mapa_titulo + 8
        limite_rodape = 270
        altura_disponivel = max(35, limite_rodape - y_mapa)
        altura_mapa = min(70, altura_disponivel)

        mapa_titulo = QgsLayoutItemLabel(layout)
        mapa_titulo.setText('Mapa da área')
        mapa_titulo.setFont(QFont('Arial', 11, QFont.Bold))
        mapa_titulo.setFontColor(cor_principal)
        mapa_titulo.adjustSizeToText()
        mapa_titulo.attemptMove(QgsLayoutPoint(15, y_mapa_titulo, QgsUnitTypes.LayoutMillimeters))
        layout.addLayoutItem(mapa_titulo)

        mapa = QgsLayoutItemMap(layout)
        mapa.attemptMove(QgsLayoutPoint(15, y_mapa, QgsUnitTypes.LayoutMillimeters))
        mapa.attemptResize(QgsLayoutSize(180, altura_mapa, QgsUnitTypes.LayoutMillimeters))
        mapa.setFrameEnabled(True)

        layers_canvas = list(self.iface.mapCanvas().layers())
        if layers_canvas:
            mapa.setLayers(layers_canvas)
        else:
            mapa.setLayers([layer])

        extent = resumo['extent'] if resumo['extent'] is not None else layer.extent()
        if not extent.isEmpty():
            extent.scale(1.10)
            mapa.setExtent(extent)

        layout.addLayoutItem(mapa)

        rodape = QgsLayoutItemLabel(layout)
        rodape.setText('Plugin Resumo de Camada - Relatório automático QGIS')
        rodape.setFont(QFont('Arial', 7))
        rodape.setFontColor(cor_texto)
        rodape.adjustSizeToText()
        rodape.attemptMove(
            QgsLayoutPoint(15, y_mapa + altura_mapa + 4, QgsUnitTypes.LayoutMillimeters)
        )
        layout.addLayoutItem(rodape)

        exporter = QgsLayoutExporter(layout)
        settings = QgsLayoutExporter.PdfExportSettings()
        resultado = exporter.exportToPdf(caminho_pdf, settings)

        if resultado == QgsLayoutExporter.Success:
            QMessageBox.information(
                self.iface.mainWindow(),
                'Resumo de Camada',
                f'PDF exportado com sucesso:\n{caminho_pdf}'
            )
        else:
            QMessageBox.critical(
                self.iface.mainWindow(),
                'Resumo de Camada',
                'Falha ao exportar PDF.'
            )

    def run(self):
        layer = self.iface.activeLayer()

        if layer is None:
            QMessageBox.warning(
                self.iface.mainWindow(),
                'Resumo de Camada',
                'Nenhuma camada ativa foi selecionada.'
            )
            return

        if layer.type() != QgsMapLayerType.VectorLayer:
            QMessageBox.warning(
                self.iface.mainWindow(),
                'Resumo de Camada',
                'Selecione uma camada vetorial ativa.'
            )
            return

        resumo = self.obter_resumo(layer)

        dlg = ResumoCamadaDialog(self.iface.mainWindow())
        dlg.preencher_dados(self.dados_dialogo(resumo))
        dlg.definir_callbacks(
            callback_pdf=lambda: self.exportar_pdf(layer, resumo),
            callback_csv=lambda: self.exportar_csv(resumo)
        )
        dlg.exec_()