# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ResumoCamadaDialog
                                 A QGIS plugin
 Mostra resumo da camada ativa e exporta CSV e PDF.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-27
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Leandro Eloi
        email                : leandroodev001@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets


FORM_CLASS, _ = uic.loadUiType(
    os.path.join(os.path.dirname(__file__), 'resumo_camada_dialog_base.ui')
)


class ResumoCamadaDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        super(ResumoCamadaDialog, self).__init__(parent)
        self.setupUi(self)

        self.btnFechar.clicked.connect(self.close)

        self._callback_pdf = None
        self._callback_csv = None

        self.btnExportarPdf.clicked.connect(self._ao_clicar_pdf)
        self.btnExportarCsv.clicked.connect(self._ao_clicar_csv)

    def definir_callbacks(self, callback_pdf=None, callback_csv=None):
        self._callback_pdf = callback_pdf
        self._callback_csv = callback_csv

    def preencher_dados(self, dados):
        camada = self._texto(dados.get('camada'))
        geometria = self._texto(dados.get('geometria'))
        feicoes = self._texto(dados.get('feicoes'))
        data_geracao = self._texto(dados.get('data'))

        self.titleLabel.setText('Resumo de Camada')
        self.subtitleLabel.setText(
            f'Camada: {camada} | Geometria: {geometria} | Feições: {feicoes}'
        )
        self.dataGeracaoLabel.setText(f'Gerado em: {data_geracao}')

        self.lblCamadaValor.setText(camada)
        self.lblEscopoValor.setText(self._texto(dados.get('escopo')))
        self.lblGeometriaValor.setText(geometria)

        self.lblFeicoesValor.setText(feicoes)
        self.lblAreaM2Valor.setText(self._texto(dados.get('area_m2')))
        self.lblAreaHaValor.setText(self._texto(dados.get('area_ha')))
        self.lblAreaKm2Valor.setText(self._texto(dados.get('area_km2')))

        self.lblDifM2Valor.setText(self._texto(dados.get('dif_m2')))
        self.lblDifHaValor.setText(self._texto(dados.get('dif_ha')))
        self.lblDifKm2Valor.setText(self._texto(dados.get('dif_km2')))

        observacao = dados.get('obs_comparacao')
        if observacao:
            self.lblObservacaoComparacao.setText(str(observacao))
        else:
            self.lblObservacaoComparacao.setText(
                'Preenchido automaticamente quando houver 2 áreas para comparar.'
            )

    def _ao_clicar_pdf(self):
        if callable(self._callback_pdf):
            self._callback_pdf()

    def _ao_clicar_csv(self):
        if callable(self._callback_csv):
            self._callback_csv()

    def _texto(self, valor, padrao='-'):
        if valor is None:
            return padrao
        texto = str(valor).strip()
        return texto if texto else padrao