# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ResumoCamada
                                 A QGIS plugin
 Mostra resumo da camada ativa e exporta CSV e PDF.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-27
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Leandro Eloi
        email                : leandroodev001@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import csv
import os
from datetime import datetime

from qgis.PyQt.QtCore import QCoreApplication, QSettings, QTranslator
from qgis.PyQt.QtGui import QColor, QFont, QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog, QMessageBox

from qgis.core import (
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransform,
    QgsFillSymbol,
    QgsGeometry,
    QgsLayoutExporter,
    QgsLayoutItemLabel,
    QgsLayoutItemMap,
    QgsLayoutItemPage,
    QgsLayoutItemPicture,
    QgsLayoutPoint,
    QgsLayoutSize,
    QgsMapLayerType,
    QgsPrintLayout,
    QgsProject,
    QgsRectangle,
    QgsSingleSymbolRenderer,
    QgsUnitTypes,
)

from .resources import *
from .resumo_camada_dialog import ResumoCamadaDialog


class ResumoCamada:
    """QGIS Plugin Implementation."""

    PAGE_WIDTH_MM = 210.0
    PAGE_HEIGHT_MM = 297.0
    PAGE_MARGIN_MM = 15.0

    def __init__(self, iface):
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)

        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'ResumoCamada_{}.qm'.format(locale)
        )

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr(u'&Resumo de Camada')
        self.first_start = None

    def tr(self, message):
        return QCoreApplication.translate('ResumoCamada', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None
    ):
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        icon_path = ':/plugins/resumo_camada/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Resumo de Camada'),
            callback=self.run,
            parent=self.iface.mainWindow()
        )
        self.first_start = True

    def unload(self):
        for action in self.actions:
            self.iface.removePluginMenu(self.tr(u'&Resumo de Camada'), action)
            self.iface.removeToolBarIcon(action)

    def tipo_geometria_texto(self, layer):
        tipos = {
            0: 'Ponto',
            1: 'Linha',
            2: 'Polígono',
            4: 'Sem geometria'
        }
        return tipos.get(layer.geometryType(), 'Desconhecido')

    def formatar_numero_br(self, valor, casas=2):
        texto = f'{valor:,.{casas}f}'
        return texto.replace(',', 'X').replace('.', ',').replace('X', '.')

    def obter_feicoes_relatorio(self, layer):
        if layer.selectedFeatureCount() > 0:
            return list(layer.selectedFeatures()), 'Feições selecionadas'
        return list(layer.getFeatures()), 'Todas as feições da camada'

    def obter_extent_feicoes(self, feicoes):
        extent = None
        for feat in feicoes:
            if not feat.hasGeometry():
                continue
            geom = feat.geometry()
            if not geom or geom.isEmpty():
                continue
            bbox = geom.boundingBox()
            if extent is None:
                extent = QgsRectangle(bbox)
            else:
                extent.combineExtentWith(bbox)
        return extent

    def transformar_extent_para_projeto(self, extent, origem_crs):
        projeto = QgsProject.instance()
        destino_crs = projeto.crs()

        if extent is None:
            return None

        rect = QgsRectangle(extent)

        if origem_crs == destino_crs:
            return rect

        try:
            transform = QgsCoordinateTransform(origem_crs, destino_crs, projeto)
            return transform.transformBoundingBox(rect)
        except Exception:
            return rect

    def obter_crs_area(self, layer, feicoes):
        projeto = QgsProject.instance()
        crs_geo = QgsCoordinateReferenceSystem('EPSG:4326')

        extent_ref = self.obter_extent_feicoes(feicoes)
        if extent_ref is None or extent_ref.isEmpty():
            extent_ref = layer.extent()

        centro = extent_ref.center()

        if layer.crs() != crs_geo:
            transform = QgsCoordinateTransform(layer.crs(), crs_geo, projeto)
            centro = transform.transform(centro)

        lon = centro.x()
        lat = centro.y()
        zona = int((lon + 180) / 6) + 1

        if lat >= 0:
            epsg = 32600 + zona
        else:
            epsg = 32700 + zona

        return QgsCoordinateReferenceSystem(f'EPSG:{epsg}')

    def analisar_feicoes(self, layer):
        projeto = QgsProject.instance()
        crs_geo = QgsCoordinateReferenceSystem('EPSG:4326')

        feicoes, escopo = self.obter_feicoes_relatorio(layer)
        crs_area = self.obter_crs_area(layer, feicoes)

        transform_area = None
        transform_geo = None

        if layer.crs() != crs_area:
            transform_area = QgsCoordinateTransform(layer.crs(), crs_area, projeto)

        if layer.crs() != crs_geo:
            transform_geo = QgsCoordinateTransform(layer.crs(), crs_geo, projeto)

        detalhes = []
        area_total_m2 = 0.0
        extent_mapa = None

        for i, feat in enumerate(feicoes, start=1):
            if not feat.hasGeometry():
                continue

            geom_original = QgsGeometry(feat.geometry())
            if not geom_original or geom_original.isEmpty():
                continue

            bbox_mapa = self.transformar_extent_para_projeto(
                geom_original.boundingBox(),
                layer.crs()
            )

            if bbox_mapa is not None:
                if extent_mapa is None:
                    extent_mapa = QgsRectangle(bbox_mapa)
                else:
                    extent_mapa.combineExtentWith(bbox_mapa)

            area_m2 = 0.0
            perimetro_m = 0.0

            if layer.geometryType() == 2:
                geom_area = QgsGeometry(geom_original)
                if transform_area is not None:
                    geom_area.transform(transform_area)
                area_m2 = abs(geom_area.area())
                perimetro_m = abs(geom_area.length())

            geom_geo = QgsGeometry(geom_original)
            if transform_geo is not None:
                geom_geo.transform(transform_geo)

            centroide_geom = geom_geo.centroid()
            if centroide_geom and not centroide_geom.isEmpty():
                centroide = centroide_geom.asPoint()
                centroide_lon = centroide.x()
                centroide_lat = centroide.y()
            else:
                bbox_geo = geom_geo.boundingBox()
                centro = bbox_geo.center()
                centroide_lon = centro.x()
                centroide_lat = centro.y()

            detalhes.append({
                'indice': i,
                'feature_id': feat.id(),
                'area_m2': area_m2,
                'perimetro_m': perimetro_m,
                'area_m2_txt': f"{self.formatar_numero_br(area_m2, 2)} m²",
                'area_ha_txt': f"{self.formatar_numero_br(area_m2 / 10000.0, 4)} ha",
                'area_km2_txt': f"{self.formatar_numero_br(area_m2 / 1000000.0, 6)} km²",
                'perimetro_txt': f"{self.formatar_numero_br(perimetro_m, 2)} m",
                'centroide_lon': centroide_lon,
                'centroide_lat': centroide_lat,
                'centroide_lat_txt': self.formatar_numero_br(centroide_lat, 6),
                'centroide_lon_txt': self.formatar_numero_br(centroide_lon, 6)
            })

            area_total_m2 += area_m2

        diff_m2 = None
        if len(detalhes) >= 2:
            diff_m2 = abs(detalhes[0]['area_m2'] - detalhes[1]['area_m2'])

        return detalhes, escopo, area_total_m2, diff_m2, extent_mapa

    def obter_resumo(self, layer):
        detalhes, escopo, area_total_m2, diff_m2, extent = self.analisar_feicoes(layer)

        resumo = {
            'nome_camada': layer.name(),
            'total_feicoes': len(detalhes),
            'tipo_geometria': self.tipo_geometria_texto(layer),
            'data_exportacao': datetime.now().strftime('%d/%m/%Y %H:%M:%S'),
            'escopo': escopo,
            'detalhes': detalhes,
            'extent': extent,
            'area_total_m2': area_total_m2,
            'area_total_m2_txt': f"{self.formatar_numero_br(area_total_m2, 2)} m²",
            'area_total_ha_txt': f"{self.formatar_numero_br(area_total_m2 / 10000.0, 4)} ha",
            'area_total_km2_txt': f"{self.formatar_numero_br(area_total_m2 / 1000000.0, 6)} km²",
            'diferenca_m2': diff_m2,
            'diferenca_m2_txt': None,
            'diferenca_ha_txt': None,
            'diferenca_km2_txt': None
        }

        if diff_m2 is not None:
            resumo['diferenca_m2_txt'] = f"{self.formatar_numero_br(diff_m2, 2)} m²"
            resumo['diferenca_ha_txt'] = f"{self.formatar_numero_br(diff_m2 / 10000.0, 4)} ha"
            resumo['diferenca_km2_txt'] = f"{self.formatar_numero_br(diff_m2 / 1000000.0, 6)} km²"

        return resumo

    def resumo_texto(self, resumo):
        linhas = [
            f"Camada: {resumo['nome_camada']}",
            f"Escopo: {resumo['escopo']}",
            f"Feições: {resumo['total_feicoes']}",
            f"Geometria: {resumo['tipo_geometria']}",
            f"Data: {resumo['data_exportacao']}",
            f"Área total: {resumo['area_total_m2_txt']}",
            f"Área total em hectares: {resumo['area_total_ha_txt']}",
            f"Área total em km²: {resumo['area_total_km2_txt']}"
        ]

        if resumo['diferenca_m2_txt'] is not None:
            linhas.extend([
                f"Diferença área 1 x área 2: {resumo['diferenca_m2_txt']}",
                f"Diferença em hectares: {resumo['diferenca_ha_txt']}",
                f"Diferença em km²: {resumo['diferenca_km2_txt']}"
            ])

        return '\n'.join(linhas)

    def texto_area_card(self, det):
        return (
            f"Tamanho: {det['area_m2_txt']}\n"
            f"Hectares: {det['area_ha_txt']}\n"
            f"Km²: {det['area_km2_txt']}\n"
            f"Perímetro: {det['perimetro_txt']}\n"
            f"Latitude: {det['centroide_lat_txt']}\n"
            f"Longitude: {det['centroide_lon_txt']}"
        )

    def dados_dialogo(self, resumo):
        if resumo['diferenca_m2_txt'] is not None:
            obs = 'Comparação calculada entre as duas primeiras áreas do relatório.'
            dif_m2 = resumo['diferenca_m2_txt']
            dif_ha = resumo['diferenca_ha_txt']
            dif_km2 = resumo['diferenca_km2_txt']
        else:
            obs = 'A comparação é exibida automaticamente quando houver pelo menos 2 áreas.'
            dif_m2 = '-'
            dif_ha = '-'
            dif_km2 = '-'

        return {
            'camada': resumo['nome_camada'],
            'escopo': resumo['escopo'],
            'feicoes': str(resumo['total_feicoes']),
            'geometria': resumo['tipo_geometria'],
            'data': resumo['data_exportacao'],
            'area_m2': resumo['area_total_m2_txt'],
            'area_ha': resumo['area_total_ha_txt'],
            'area_km2': resumo['area_total_km2_txt'],
            'dif_m2': dif_m2,
            'dif_ha': dif_ha,
            'dif_km2': dif_km2,
            'obs_comparacao': obs
        }

    def exportar_csv(self, resumo):
        caminho_csv, _ = QFileDialog.getSaveFileName(
            self.iface.mainWindow(),
            'Salvar resumo em CSV',
            f"{resumo['nome_camada']}_resumo.csv",
            'CSV (*.csv)'
        )

        if not caminho_csv:
            return

        if not caminho_csv.lower().endswith('.csv'):
            caminho_csv += '.csv'

        with open(caminho_csv, 'w', newline='', encoding='utf-8-sig') as arquivo:
            writer = csv.writer(arquivo)

            writer.writerow(['Resumo da Camada'])
            writer.writerow(['Camada', resumo['nome_camada']])
            writer.writerow(['Escopo', resumo['escopo']])
            writer.writerow(['Feições', resumo['total_feicoes']])
            writer.writerow(['Geometria', resumo['tipo_geometria']])
            writer.writerow(['Data', resumo['data_exportacao']])
            writer.writerow(['Área total', resumo['area_total_m2_txt']])
            writer.writerow(['Área total em hectares', resumo['area_total_ha_txt']])
            writer.writerow(['Área total em km²', resumo['area_total_km2_txt']])

            if resumo['diferenca_m2_txt'] is not None:
                writer.writerow(['Diferença área 1 x área 2', resumo['diferenca_m2_txt']])

            writer.writerow([])
            writer.writerow([
                'Área',
                'Feature ID',
                'Área m²',
                'Área ha',
                'Área km²',
                'Perímetro',
                'Latitude',
                'Longitude'
            ])

            for det in resumo['detalhes']:
                writer.writerow([
                    f"Área {det['indice']}",
                    det['feature_id'],
                    det['area_m2_txt'],
                    det['area_ha_txt'],
                    det['area_km2_txt'],
                    det['perimetro_txt'],
                    det['centroide_lat_txt'],
                    det['centroide_lon_txt']
                ])

        QMessageBox.information(
            self.iface.mainWindow(),
            'Resumo de Camada',
            f'CSV exportado com sucesso:\n{caminho_csv}'
        )

    def configurar_estilo_layer(self, layer):
        if layer.geometryType() != 2:
            return

        simbolo = QgsFillSymbol.createSimple({
            'color': '255,215,64,100',
            'outline_color': '120,80,0,255',
            'outline_width': '0.9'
        })
        layer.setRenderer(QgsSingleSymbolRenderer(simbolo))
        layer.triggerRepaint()

    def _page_y(self, pagina, y_local):
        return (pagina * self.PAGE_HEIGHT_MM) + y_local

    def _garantir_pagina(self, layout, indice_pagina):
        while layout.pageCollection().pageCount() <= indice_pagina:
            pagina = QgsLayoutItemPage(layout)
            pagina.setPageSize('A4', QgsLayoutItemPage.Orientation.Portrait)
            layout.pageCollection().addPage(pagina)

    def _criar_label_layout(self, layout, texto, fonte, cor, x, y, largura=None):
        label = QgsLayoutItemLabel(layout)
        label.setText(texto)
        label.setFont(fonte)
        label.setFontColor(cor)
        if largura:
            label.attemptResize(QgsLayoutSize(largura, 200, QgsUnitTypes.LayoutMillimeters))
        label.adjustSizeToText()
        layout.addLayoutItem(label)
        label.attemptMove(QgsLayoutPoint(x, y, QgsUnitTypes.LayoutMillimeters))
        return label

    def _obter_extent_mapa_pdf(self, layer, resumo):
        extent = resumo.get('extent')
        if extent is None or extent.isEmpty():
            extent = self.transformar_extent_para_projeto(layer.extent(), layer.crs())

        if extent is None or extent.isEmpty():
            return None

        extent_pdf = QgsRectangle(extent)

        if extent_pdf.width() == 0:
            extent_pdf.setXMinimum(extent_pdf.xMinimum() - 10)
            extent_pdf.setXMaximum(extent_pdf.xMaximum() + 10)

        if extent_pdf.height() == 0:
            extent_pdf.setYMinimum(extent_pdf.yMinimum() - 10)
            extent_pdf.setYMaximum(extent_pdf.yMaximum() + 10)

        extent_pdf.scale(1.15)
        return extent_pdf

    def exportar_pdf(self, layer, resumo):
        caminho_pdf, _ = QFileDialog.getSaveFileName(
            self.iface.mainWindow(),
            'Salvar resumo em PDF',
            f"{resumo['nome_camada']}_resumo.pdf",
            'PDF (*.pdf)'
        )

        if not caminho_pdf:
            return

        if not caminho_pdf.lower().endswith('.pdf'):
            caminho_pdf += '.pdf'

        renderer_original = None
        if layer.renderer():
            try:
                renderer_original = layer.renderer().clone()
            except Exception:
                renderer_original = None

        try:
            self.configurar_estilo_layer(layer)

            projeto = QgsProject.instance()
            layout = QgsPrintLayout(projeto)
            layout.initializeDefaults()
            layout.setName(
                f"ResumoCamadaPDF_{resumo['nome_camada']}_{datetime.now().strftime('%H%M%S')}"
            )

            self._garantir_pagina(layout, 0)

            cor_principal = QColor(24, 91, 127)
            cor_texto = QColor(55, 55, 55)

            pagina = 0
            margem_x = self.PAGE_MARGIN_MM

            logo_path = os.path.join(self.plugin_dir, 'icon.png')
            if os.path.exists(logo_path):
                logo = QgsLayoutItemPicture(layout)
                logo.setPicturePath(logo_path)
                layout.addLayoutItem(logo)
                logo.attemptMove(QgsLayoutPoint(margem_x - 3, self._page_y(pagina, 10), QgsUnitTypes.LayoutMillimeters))
                logo.attemptResize(QgsLayoutSize(14, 14, QgsUnitTypes.LayoutMillimeters))

            self._criar_label_layout(
                layout,
                'Resumo de Camada',
                QFont('Arial', 18, QFont.Bold),
                cor_principal,
                margem_x + 15,
                self._page_y(pagina, 10)
            )

            self._criar_label_layout(
                layout,
                f"Relatório gerado em {resumo['data_exportacao']}",
                QFont('Arial', 8),
                cor_texto,
                margem_x + 15,
                self._page_y(pagina, 18)
            )

            self._criar_label_layout(
                layout,
                'Resumo geral',
                QFont('Arial', 11, QFont.Bold),
                cor_principal,
                margem_x,
                self._page_y(pagina, 34)
            )

            bloco_resumo = QgsLayoutItemLabel(layout)
            bloco_resumo.setText(self.resumo_texto(resumo))
            bloco_resumo.setFont(QFont('Arial', 8))
            bloco_resumo.adjustSizeToText()
            layout.addLayoutItem(bloco_resumo)
            bloco_resumo.attemptMove(
                QgsLayoutPoint(margem_x, self._page_y(pagina, 42), QgsUnitTypes.LayoutMillimeters)
            )

            resumo_bottom_local = 42 + bloco_resumo.rect().height()
            detalhes = resumo['detalhes']

            cards_page = 0
            cards_y_local = resumo_bottom_local + 14
            row_height = 42
            x_inicial = margem_x
            largura_coluna = 85
            espaco_x = 10
            limite_cards_local = 250

            if detalhes:
                linhas = [detalhes[i:i + 2] for i in range(0, len(detalhes), 2)]

                for idx_linha, linha in enumerate(linhas):
                    if cards_y_local + row_height > limite_cards_local:
                        cards_page += 1
                        self._garantir_pagina(layout, cards_page)

                        self._criar_label_layout(
                            layout,
                            'Áreas do relatório',
                            QFont('Arial', 11, QFont.Bold),
                            cor_principal,
                            margem_x,
                            self._page_y(cards_page, 15)
                        )
                        cards_y_local = 24

                    for col, det in enumerate(linha):
                        x = x_inicial + col * (largura_coluna + espaco_x)
                        y = self._page_y(cards_page, cards_y_local)

                        self._criar_label_layout(
                            layout,
                            f"Área {det['indice']} (ID {det['feature_id']})",
                            QFont('Arial', 10, QFont.Bold),
                            cor_principal,
                            x,
                            y
                        )

                        area_texto = QgsLayoutItemLabel(layout)
                        area_texto.setText(self.texto_area_card(det))
                        area_texto.setFont(QFont('Arial', 8))
                        area_texto.adjustSizeToText()
                        layout.addLayoutItem(area_texto)
                        area_texto.attemptMove(
                            QgsLayoutPoint(x, y + 8, QgsUnitTypes.LayoutMillimeters)
                        )

                    cards_y_local += row_height
            else:
                self._criar_label_layout(
                    layout,
                    'Nenhuma feição válida foi encontrada para o relatório.',
                    QFont('Arial', 8),
                    cor_texto,
                    margem_x,
                    self._page_y(cards_page, cards_y_local)
                )

            pagina_mapa = cards_page + 1
            self._garantir_pagina(layout, pagina_mapa)

            self._criar_label_layout(
                layout,
                'Mapa da área',
                QFont('Arial', 11, QFont.Bold),
                cor_principal,
                margem_x,
                self._page_y(pagina_mapa, 15)
            )

            self._criar_label_layout(
                layout,
                f"Camada: {resumo['nome_camada']}",
                QFont('Arial', 8),
                cor_texto,
                margem_x,
                self._page_y(pagina_mapa, 23)
            )

            mapa = QgsLayoutItemMap(layout)
            layout.addLayoutItem(mapa)
            mapa.attemptMove(
                QgsLayoutPoint(margem_x, self._page_y(pagina_mapa, 32), QgsUnitTypes.LayoutMillimeters)
            )
            mapa.attemptResize(QgsLayoutSize(180, 165, QgsUnitTypes.LayoutMillimeters))
            mapa.setFrameEnabled(True)

            try:
                mapa.setBackgroundEnabled(True)
                mapa.setBackgroundColor(QColor(255, 255, 255))
            except Exception:
                pass

            mapa.setLayers([layer])

            try:
                mapa.setKeepLayerSet(True)
            except Exception:
                pass

            extent_pdf = self._obter_extent_mapa_pdf(layer, resumo)
            if extent_pdf is not None:
                mapa.setExtent(extent_pdf)

            mapa.refresh()

            rodape = QgsLayoutItemLabel(layout)
            rodape.setText('Plugin Resumo de Camada - Relatório automático QGIS')
            rodape.setFont(QFont('Arial', 7))
            rodape.setFontColor(cor_texto)
            rodape.adjustSizeToText()
            layout.addLayoutItem(rodape)
            rodape.attemptMove(
                QgsLayoutPoint(margem_x, self._page_y(pagina_mapa, 282), QgsUnitTypes.LayoutMillimeters)
            )

            exporter = QgsLayoutExporter(layout)
            settings = QgsLayoutExporter.PdfExportSettings()
            resultado = exporter.exportToPdf(caminho_pdf, settings)

            if resultado == QgsLayoutExporter.Success:
                QMessageBox.information(
                    self.iface.mainWindow(),
                    'Resumo de Camada',
                    f'PDF exportado com sucesso:\n{caminho_pdf}'
                )
            else:
                QMessageBox.critical(
                    self.iface.mainWindow(),
                    'Resumo de Camada',
                    'Falha ao exportar PDF.'
                )

        finally:
            if renderer_original is not None:
                layer.setRenderer(renderer_original)
                layer.triggerRepaint()

    def run(self):
        layer = self.iface.activeLayer()

        if layer is None:
            QMessageBox.warning(
                self.iface.mainWindow(),
                'Resumo de Camada',
                'Nenhuma camada ativa foi selecionada.'
            )
            return

        if layer.type() != QgsMapLayerType.VectorLayer:
            QMessageBox.warning(
                self.iface.mainWindow(),
                'Resumo de Camada',
                'Selecione uma camada vetorial ativa.'
            )
            return

        resumo = self.obter_resumo(layer)

        dlg = ResumoCamadaDialog(self.iface.mainWindow())
        dlg.preencher_dados(self.dados_dialogo(resumo))
        dlg.definir_callbacks(
            callback_pdf=lambda: self.exportar_pdf(layer, resumo),
            callback_csv=lambda: self.exportar_csv(resumo)
        )
        dlg.exec_()